Database First Approach- Entity Framework/CRUD_DatabaseFirstApproachEF/CRUD_DatabaseFirstApproachEF/Models/Student.cs
using System;
using System.Collections.Generic;

namespace CRUD_DatabaseFirstApproachEF.Models
{
    public partial class Student
    {
        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public string Gender { get; set; } = null!;
        public int Age { get; set; }
        public int Class { get; set; }
    }
}

Database First Approach- Entity Framework/CRUD_DatabaseFirstApproachEF/CRUD_DatabaseFirstApproachEF/Controllers/ParentsDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRUD_DatabaseFirstApproachEF.Models;

namespace CRUD_DatabaseFirstApproachEF.Controllers
{
    public class ParentsDetailsController : Controller
    {
        private readonly CRUD_DatabaseFirstApproach_DBContext _context;

        public ParentsDetailsController(CRUD_DatabaseFirstApproach_DBContext context)
        {
            _context = context;
        }

        // GET: ParentsDetails
        public async Task<IActionResult> Index()
        {
              return _context.StdParentsDetailsTbls != null ? 
                          View(await _context.StdParentsDetailsTbls.ToListAsync()) :
                          Problem("Entity set 'CRUD_DatabaseFirstApproach_DBContext.StdParentsDetailsTbls'  is null.");
        }

        // GET: ParentsDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.StdParentsDetailsTbls == null)
            {
                return NotFound();
            }

            var stdParentsDetailsTbl = await _context.StdParentsDetailsTbls
                .FirstOrDefaultAsync(m => m.Id == id);
            if (stdParentsDetailsTbl == null)
            {
                return NotFound();
            }

            return View(stdParentsDetailsTbl);
        }

        // GET: ParentsDetails/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ParentsDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FatherName,MotherName,Address")] StdParentsDetailsTbl stdParentsDetailsTbl)
        {
            if (ModelState.IsValid)
            {
                _context.Add(stdParentsDetailsTbl);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(stdParentsDetailsTbl);
        }

        // GET: ParentsDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.StdParentsDetailsTbls == null)
            {
                return NotFound();
            }

            var stdParentsDetailsTbl = await _context.StdParentsDetailsTbls.FindAsync(id);
            if (stdParentsDetailsTbl == null)
            {
                return NotFound();
            }
            return View(stdParentsDetailsTbl);
        }

        // POST: ParentsDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FatherName,MotherName,Address")] StdParentsDetailsTbl stdParentsDetailsTbl)
        {
            if (id != stdParentsDetailsTbl.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(stdParentsDetailsTbl);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StdParentsDetailsTblExists(stdParentsDetailsTbl.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(stdParentsDetailsTbl);
        }

        // GET: ParentsDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.StdParentsDetailsTbls == null)
            {
                return NotFound();
            }

            var stdParentsDetailsTbl = await _context.StdParentsDetailsTbls
                .FirstOrDefaultAsync(m => m.Id == id);
            if (stdParentsDetailsTbl == null)
            {
                return NotFound();
            }

            return View(stdParentsDetailsTbl);
        }

        // POST: ParentsDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.StdParentsDetailsTbls == null)
            {
                return Problem("Entity set 'CRUD_DatabaseFirstApproach_DBContext.StdParentsDetailsTbls'  is null.");
            }
            var stdParentsDetailsTbl = await _context.StdParentsDetailsTbls.FindAsync(id);
            if (stdParentsDetailsTbl != null)
            {
                _context.StdParentsDetailsTbls.Remove(stdParentsDetailsTbl);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StdParentsDetailsTblExists(int id)
        {
          return (_context.StdParentsDetailsTbls?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Database First Approach- Entity Framework/CRUD_DatabaseFirstApproachEF/CRUD_DatabaseFirstApproachEF/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRUD_DatabaseFirstApproachEF.Models;

namespace CRUD_DatabaseFirstApproachEF.Controllers
{
    public class StudentsController : Controller
    {
        private readonly CRUD_DatabaseFirstApproach_DBContext _context;

        public StudentsController(CRUD_DatabaseFirstApproach_DBContext context)
        {
            _context = context;
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
              return _context.Students != null ? 
                          View(await _context.Students.ToListAsync()) :
                          Problem("Entity set 'CRUD_DatabaseFirstApproach_DBContext.Students'  is null.");
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Gender,Age,Class")] Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var student = await _context.Students.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Gender,Age,Class")] Student student)
        {
            if (id != student.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Students == null)
            {
                return Problem("Entity set 'CRUD_DatabaseFirstApproach_DBContext.Students'  is null.");
            }
            var student = await _context.Students.FindAsync(id);
            if (student != null)
            {
                _context.Students.Remove(student);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentExists(int id)
        {
          return (_context.Students?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Database First Approach- Entity Framework/CRUD_DatabaseFirstApproachEF/CRUD_DatabaseFirstApproachEF/Views/Students/Create.cshtml
@model CRUD_DatabaseFirstApproachEF.Models.Student

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Class" class="control-label"></label>
                <input asp-for="Class" class="form-control" />
                <span asp-validation-for="Class" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Database First Approach- Entity Framework/CRUD_DatabaseFirstApproachEF/CRUD_DatabaseFirstApproachEF/Views/Students/Delete.cshtml
@model CRUD_DatabaseFirstApproachEF.Models.Student

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Class)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Class)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Database First Approach- Entity Framework/CRUD_DatabaseFirstApproachEF/CRUD_DatabaseFirstApproachEF/Views/Students/Details.cshtml
@model CRUD_DatabaseFirstApproachEF.Models.Student

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Student</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Class)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Class)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Database First Approach- Entity Framework/CRUD_DatabaseFirstApproachEF/CRUD_DatabaseFirstApproachEF/Views/Students/Edit.cshtml
@model CRUD_DatabaseFirstApproachEF.Models.Student

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Class" class="control-label"></label>
                <input asp-for="Class" class="form-control" />
                <span asp-validation-for="Class" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Database First Approach- Entity Framework/CRUD_DatabaseFirstApproachEF/CRUD_DatabaseFirstApproachEF/Views/Students/Index.cshtml
@model IEnumerable<CRUD_DatabaseFirstApproachEF.Models.Student>


@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<p>
    <a asp-controller="ParentsDetails" asp-action="Index">Go to parents</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Class)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Class)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
